### ISSUE TITLE
Small null pointers found

### ISSUE THREAD

**Issue by TheLimeGlass** [JordanOsterberg/SkywarsSeries#1]
Heyo. Found two null pointers thrown when looking and testing stuff.

~~https://github.com/JordanOsterberg/SkywarsSeries/blob/master/src/main/java/tech/shadowsystems/skywars/Skywars.java#L87-L97~~

~~Check if there are no players in the server/world before doing the method.~~
Edit: Was issue with getLobbyPoint()

and https://github.com/JordanOsterberg/SkywarsSeries/blob/master/src/main/java/tech/shadowsystems/skywars/data/DataHandler.java#L21-L25

Making a directory for the file if the directory is not found
```
try {
	this.gameInfoFile.getParentFile().mkdirs();
	this.gameInfoFile.createNewFile();
} catch (IOException e) {
	e.printStackTrace();
}
```

Love your videos. You should make more videos xD Keep up the great work. Been sub since like 500

Suggestion if you're still doing the series: kits?

Thanks. <3

**Comment by JordanOsterberg** [comment]
Fixed!
